### List containers
GET http://localhost:3000/api/rooms
Authorization: Bearer DONT_USE_THIS_TOKEN

### Get mapped ports
GET https://localhost:9443/api/ports
Authorization: Bearer DONT_USE_THIS_TOKEN

### Get free port
POST https://localhost:9443/api/ports/free
Authorization: Bearer DONT_USE_THIS_TOKEN
Content-Type: application/json

{ 
  "protocol": "tcp",
  "lowerBound": 9000,
  "count": 1,
  "upperBound": 10000
}

### Create room 1
POST http://localhost:3000/api/neko
Authorization: Bearer DONT_USE_THIS_TOKEN
Content-Type: application/json

{
  "name": "neko_10.A",
  "maxMembers": 10
}

### Test room 1 (add to /etc/localhost first)
GET https://neko_10.A.localhost:9443

### Delete room 1
DELETE https://localhost:9443/api/neko/neko_10.A
Authorization: Bearer DONT_USE_THIS_TOKEN

